Repository gdcc/python-dvuploader, pull requests merged in 2025-02, with the labels that each got.

#21 Parallel hash calculation and progress bar fix
  dvuploader/checksum.py
  dvuploader/cli.py
  dvuploader/directupload.py
  dvuploader/dvuploader.py
  dvuploader/file.py
  dvuploader/nativeupload.py
  dvuploader/packaging.py
  dvuploader/utils.py
  tests/integration/test_native_upload.py
  tests/unit/test_cli.py
  tests/unit/test_file.py
  tests/unit/test_utils.py
Labels: bug, enhancement

#26 Remove the strict typer dependency
  pyproject.toml
Labels: enhancement

#27 Add CLI input checks
  .github/workflows/test.yml
  dvuploader/cli.py
Labels: bug

#23 Add proxy option to `upload` method
  .github/workflows/test.yml
  dvuploader/directupload.py
  dvuploader/dvuploader.py
  dvuploader/nativeupload.py
  tests/integration/test_native_upload.py
Labels: bug, enhancement
